#
# This file is part of the m2-kiosk-ansible distribution (https://github.com/M2tec/m2_kiosk_ansible).
# Copyright (c) 2023 Maarten Menheere.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

- name: Install packages
  hosts: m2paypad
  become: yes
  vars: 
    dest_path: /tmp/latest/

  tasks:
  - name: Ping my hosts
    ansible.builtin.ping:   

  - name: Installing m2tec repo key
    shell: "curl -sS https://packages.m2tec.nl/packages.m2tec.gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/m2tec.gpg"
    register: command_result

  - name: Installing m2tec apt repo
    shell: 'echo "deb https://packages.m2tec.nl/apt/ bullseye stable" | sudo tee /etc/apt/sources.list.d/m2tec.list'
    register: command_result

  - name: Update apt-get repo and cache
    apt: 
      update_cache=yes 
          
  - name: Install packages apt
    apt:
      pkg:
        - m2-kiosk-app
        - m2-kiosk-desktop
        - m2-kiosk-web

  - name: Unconditionally reboot the machine with all defaults
    ansible.builtin.reboot:
